# Generated by Django 4.1.7 on 2023-02-17 22:27

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gisapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Counties",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("adm0_en", models.CharField(max_length=50)),
                ("adm0_ar", models.CharField(max_length=50)),
                ("adm0_pcode", models.CharField(max_length=50)),
                ("adm0_ref", models.CharField(max_length=50)),
                ("adm0alt1en", models.CharField(max_length=50)),
                ("adm0alt2en", models.CharField(max_length=50)),
                ("adm0alt1ar", models.CharField(max_length=50)),
                ("adm0alt2ar", models.CharField(max_length=50)),
                ("date", models.DateField()),
                ("validon", models.DateField()),
                ("validto", models.DateField()),
                ("shape_leng", models.FloatField()),
                ("shape_area", models.FloatField()),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
            ],
        ),
    ]
