# Generated by Django 4.1.7 on 2023-02-17 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gisapp", "0002_counties"),
    ]

    operations = [
        migrations.AlterField(
            model_name="counties",
            name="adm0alt1en",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
