# Generated by Django 4.1.7 on 2023-02-17 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gisapp", "0003_alter_counties_adm0alt1en"),
    ]

    operations = [
        migrations.AlterField(
            model_name="counties",
            name="adm0_ar",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="counties",
            name="adm0_en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="counties",
            name="adm0_pcode",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="counties",
            name="adm0_ref",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="counties",
            name="adm0alt1ar",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="counties",
            name="adm0alt2ar",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="counties",
            name="adm0alt2en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="counties",
            name="date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="counties",
            name="shape_area",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="counties",
            name="shape_leng",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="counties",
            name="validon",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="counties",
            name="validto",
            field=models.DateField(null=True),
        ),
    ]
