# Generated by Django 4.1.7 on 2023-02-17 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gisapp", "0005_provinces"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provinces",
            name="adm0_ar",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="provinces",
            name="adm0_en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="provinces",
            name="adm0_pcode",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="provinces",
            name="adm1_ar",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="provinces",
            name="adm1_en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="provinces",
            name="adm1_pcode",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="provinces",
            name="adm1_ref",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="provinces",
            name="adm1alt1ar",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="provinces",
            name="adm1alt1en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="provinces",
            name="adm1alt2ar",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="provinces",
            name="adm1alt2en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="provinces",
            name="date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="provinces",
            name="shape_area",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="provinces",
            name="shape_leng",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="provinces",
            name="validon",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="provinces",
            name="validto",
            field=models.DateField(null=True),
        ),
    ]
