# Generated by Django 4.1.6 on 2023-02-19 02:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gisapp", "0006_alter_provinces_adm0_ar_alter_provinces_adm0_en_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Strite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("med_descri", models.CharField(max_length=254)),
                ("rtt_descri", models.CharField(max_length=254)),
                ("f_code_des", models.CharField(max_length=10)),
                ("iso", models.CharField(max_length=7)),
                ("isocountry", models.CharField(max_length=54)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326),
                ),
            ],
        ),
    ]
