# Generated by Django 4.1.6 on 2023-02-19 02:08

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gisapp", "0007_strite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strite",
            name="f_code_des",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="strite",
            name="geom",
            field=django.contrib.gis.db.models.fields.MultiLineStringField(
                null=True, srid=4326
            ),
        ),
        migrations.AlterField(
            model_name="strite",
            name="iso",
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name="strite",
            name="isocountry",
            field=models.CharField(max_length=54, null=True),
        ),
        migrations.AlterField(
            model_name="strite",
            name="med_descri",
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="strite",
            name="rtt_descri",
            field=models.CharField(max_length=254, null=True),
        ),
    ]
