# Generated by Django 4.1.6 on 2023-02-19 02:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gisapp", "0009_strite2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strite2",
            name="geom",
            field=django.contrib.gis.db.models.fields.MultiLineStringField(
                null=True, srid=4326
            ),
        ),
        migrations.AlterField(
            model_name="strite2",
            name="lanes",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="strite2",
            name="name",
            field=models.CharField(max_length=113, null=True),
        ),
        migrations.AlterField(
            model_name="strite2",
            name="oneway",
            field=models.CharField(max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name="strite2",
            name="type",
            field=models.CharField(max_length=22, null=True),
        ),
    ]
